# fly.toml app configuration file generated for gaming-grids on 2024-02-05T15:27:30+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gaming-grids'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
