name: Build and Deploy Dev

permissions:
    id-token: write
    contents: read
    actions: read

on:
    push:
        branches:
            - 'main'
jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.CONTAINER_USERNAME }}
                  password: ${{ secrets.CONTAINER_PASSWORD }}
            - name: Build and Push image
              uses: docker/build-push-action@v5
              with:
                  push: true
                  build-args: |
                      GIT_SHA=${{ github.sha }}
                  tags: ${{ secrets.REPOSITORY_NAME }}/gaming-grids:develop , ${{ secrets.REPOSITORY_NAME }}/gaming-grids:${{ github.sha }}
