name: Build and Deploy Dev

on:
  push:
    branches:
      - "main"
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}
      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.REPOSITORY_NAME }}/gaming-grids:${{ github.ref_name }}
  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: docker pull ${{ secrets.REPOSITORY_NAME }}/gaming-grids:${{ github.ref_name }}
      - name: deploy
        run: |
          flyctl deploy --image ${{ secrets.REPOSITORY_NAME }}/gaming-grids:${{ github.ref_name }} \
            --image-label ${{ github.ref_name }} \
            --local-only