name: Build PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}
      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REPOSITORY_NAME }}/gaming-grids:${{ github.head_ref }}-${{ github.sha }}
